### ISSUE TITLE
Question regarding minor build number

### ISSUE THREAD

**Issue by bardware** [corretto/corretto-8#121]
I look at your downloads page: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html and see amazon-corretto-8.212.04.2-windows-x64-jdk.zip
I wonder about `04.2`. I downloaded `8.212` before and the numbers were smaller.
What are the reasons you built the JDK fresh? How do I know new minor builds are available? Do I have to check the downloads page every once in a while?

p.s. German language download page still lists `8.202`.

**Comment by navyxliu** [comment]
For tag 8.212.04.02, the last digitals is Corretto build number.  You are right, 02 means the 2nd build. 
Last week, we identified a minor defect and fixed it. That's why it has a newer build. 

Sorry for the inconsistent document in German.  It takes time to translate and proofread the documents to other languages. We are working on that.

You should download the latest version of corretto.

**Comment by bardware** [comment]
No trouble with the language page. 
It's just I have to know when to look for an updated version!
