### ISSUE TITLE
Exception sites - supported ?

### ISSUE THREAD

**Issue by michalgarcarz** [corretto/corretto-8#144]
Hello Team,

Coretto 8 + Windows 10. Trying to access Cisco ASA Firewall using ASDM and failing on certificate (SAN) validation.

I have configured exception like this:
%userprofile%\appdata\LocalLow\Sun\Java\Deployment\security\exception.sites
And put into that file URL to my ASA.
But it did not work.

It works with Oracle java. Are you able to confirm please ?
Supported ?

Thanks,
Michal

**Comment by michalgarcarz** [comment]
<img width="373" alt="Screen Shot 2019-06-17 at 15 21 43" src="https://user-images.githubusercontent.com/43064944/59607921-9368c080-9114-11e9-8541-a08f7b1138cc.png">

**Comment by alvdavi** [comment]
Hi,

The exception.sites file you mention is part of the proprietary Java WebStart framework, and it is not included in OpenJDK.

Is this a problem caused because the certificate is self signed (or signed by a CA not trusted in Corretto by default) or because the certificate subject does not match the URL we are connecting?

For the first case, the self-signed certificates (or missing CA) can be added to the Corretto trust store using keytool.

For the second case, I'm afraid there is no way to disable subject name validation. However, it some circumstances, some of these errors can be circumvented using the hosts file.

**Comment by michalgarcarz** [comment]
Thanks a lot for the answer, in our case it's the second scenario unfortunately (it's a part of the infrastructure which belongs to our customers, we have no control over that), will try the other workarounds. Thanks !
