### ISSUE TITLE
Allow JAVA_HOME and PATH to be configured from installer

### ISSUE THREAD

**Issue by EricEdens** [corretto/corretto-8#15]
@jim-pickering in #14:

> It would also be nice if Corretto would set the JAVA_HOME environment variable with the installer too. Zulu does that.

**Comment by yoroto** [comment]
This issue is fixed in the new Corretto preview release (1.8.0_192-amazon-corretto-preview2-b12). Change log of this release is now [available](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html). You can find the builds in the [Corretto download page](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html). Please let us know if you have any further questions. We appreciate your suggestion!

@Lock128 You need to use INSTALLDIR rather than TARGETDIR with the new installer for the silent install option.
