### ISSUE TITLE
error: package sun.awt.X11 does not exist

### ISSUE THREAD

**Issue by fishon-dev** [corretto/corretto-8#158]
Package sun.awt.X11.XEmbeddedFrame is checked for in IcedTea-Web for Windows (https://github.com/GITNE/icedtea-web) configure script but having Corretto 8 installed its not found as per the error in the title. Is it not included in OpenJDK8/Corretto8?

I could not find it in JDK 8 API documentation; https://docs.oracle.com/javase/8/docs/api/index.html

But I did find this code for it online here;
https://www.codesearch.cloud/openjdk/xref/jdk9u/jdk/src/java.desktop/unix/classes/sun/awt/X11/XEmbeddedFrame.java?r=11926%3A39bd7fa12bc3

And info on it here;
http://www.docjar.com/docs/api/sun/awt/X11/XEmbeddedFrame.html
https://openjdk.binarydoc.org/net.java/openjdk/11.0.0/classfile?uri_location=sun.awt.x11.xembeddedframe

If it's not included in Corretto 8 can I just implement the code found above somehow into Corretto 8 installation?

**Comment by alvdavi** [comment]
Hi,

The specific file you mention is indeed part of Corretto. It is in different path because OpenJDK8 uses solaris instead of unix in the path, and also because it was before the modularization of the code. But the file is there: 
[src/jdk/src/solaris/classes/sun/awt/X11/XEmbeddedFrame.java](https://github.com/corretto/corretto-8/blob/develop/src/jdk/src/solaris/classes/sun/awt/X11/XEmbeddedFrame.java)

The reason you did not find it in the JDK8 API documentation is that package `sun.awt` is not part of the public API. It will be used on unix systems when rendering components of the `java.awt` package.

However, I have to mention that Corretto for Windows is built without X11 support, so that file will not be included:
```
PS C:\corretto\jdk> .\bin\jar.exe -tf .\jre\lib\rt.jar  | ?{$_ -like "*sun/awt/X11/XEmbeddedFrame*"}
PS C:\corretto\jdk>
```

The same class will be present on Linux and Mac versions of Corretto:
```
$ -> jar -tf ./lib/rt.jar | grep sun/awt/X11/XEmbeddedFrame.class                                                             
sun/awt/X11/XEmbeddedFrame.class
$ ->
```

This behavior is intentional, as Windows does not include X11 support. Although there are some third party programs that add X11 support in Windows, this is mostly used to accept remote connections.

Finally, if you want to build IcedTea-web on windows, I would suggest using the official repository with the latest sources:
https://github.com/AdoptOpenJDK/icedtea-web
