### ISSUE TITLE
32 bit JVM 8.0_222 on Windows unable to start with Xmx set to 1G

### ISSUE THREAD

**Issue by pavelsher** [corretto/corretto-8#172]
### Describe the bug
Try to start some simple Main class with Xmx set to 1G with 32-bit Corretto JVM 8.0_222 and it will fail with error:
Error occurred during initialization of VM
Could not reserve enough space for 1048576KB object heap

### To Reproduce
Create a simple main class and run it with Xmx1g

### Expected behavior
It should start properly. Both Oracle and OpenJDK 8.x run without problems with even higher Xmx1200m, but Corretto already fails with 1g.

### Platform information
    OS: Windows
    Version 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment Corretto-8.222.10.3 (build 1.8.0_222-b10)
OpenJDK Server VM Corretto-8.222.10.3 (build 25.222-b10, mixed mode)

### Additional context
We wanted to bundle 32-bit Corretto JVM with our product (TeamCity), but we have lots of users who run servers in 32-bit mode with custom Xmx set to 1g or even higher. All of them will be affected by this bug, so for us it's a no go at the moment.

**Comment by yishaigalatzer** [comment]
Pavel,

Thanks for trying Corretto and reporting this issue, we will take a look.

Can you share a bit more about the version of windows you are running in, how much memory does that machine has? 

When you say a simple main class, is that just a "hello world" type application?

Can you tell us on the same machine when does the other JDKs fail (with what XMX)?

Are you able to share the full command line?

**Comment by ziyiluo** [comment]
@pavelsher I tried to run a dummy HelloWorld with `-Xmx1g` on a 4G memory Win32 host. JVM was able to start normally (even with `-Xmx1200m`). Here's the screenshot:
![Screen Shot 2019-10-10 at 11 50 58 AM](https://user-images.githubusercontent.com/14266413/66597664-4772d900-eb54-11e9-91b7-df704ea0fd85.png)

I see the same error "Error occurred during initialization of VM" with `-Xmx1400m` on my host. So it's possible that your host did not have > 1GB free memory when you observed the JVM failure. Would you please provide additional info (code snippet, command line) that may help us diagnose?

**Comment by pavelsher** [comment]
In my case this is Windows 10 Professional, version 1903 with 64Gb memory installed. Of those, 45Gb are available. OS is 64-bit. 

![image](https://user-images.githubusercontent.com/301744/66607806-59389880-ebb5-11e9-9c33-cd6db7044bf3.png)

Hello world class:
```
public class HelloWorld {

  public static void main(String[] args) {
    System.out.println("Hello!!!");
  }

}
```

Command line:
```
D:\tmp\hello>C:\Java\jdk1.8.0_222-corretto\jdk1.8.0_222\bin\java.exe -Xmx1g -cp . HelloWorld
Error occurred during initialization of VM
Could not reserve enough space for 1048576KB object heap
```

> Can you tell us on the same machine when does the other JDKs fail (with what XMX)?

Both Oracle and AdoptOpenJDK fail with Xmx set to slightly more than 1200m.

I've tried the same Hello world example on another machine, this time it was Windows 10 Home, version 1809 with the following specs:
![image](https://user-images.githubusercontent.com/301744/66608112-01e6f800-ebb6-11e9-907c-b9322322eb4c.png)

And it works perfectly fine there. I also was able to start it with Xmx1400m. But on the first one, with much bigger RAM it fails consistently.

**Comment by yoroto** [comment]
Hi @pavelsher 

Thank you for the update! We managed to reproduce this in a similar environment and are looking into fixing it.

**Comment by ziyiluo** [comment]
@pavelsher Quick update, the issue is cause by Corretto 8 32-bit build only supporting server VM mode (i.e., you cannot switch to client mode by adding `-client` flag during the startup). Our tests showed that server VM requires ~200 MB more memory than the client VM in our 32-bit Windows environment. We are working on enabling the client mode in our 32-bit Windows build. Meanwhile, we tested that disabling tiered compilation and setting the maximum code cache size to be 48M help reducing memory consumption in the server VM mode. You can try to run Corretto with:
```
java +XX:-TieredCompilation -XX:ReservedCodeCacheSize=48m -Xmx1g <your class>
```

**Comment by yoroto** [comment]
Hi @pavelsher

Can you try to disable Tiered Compilation with Corretto and try it again? The JVM parameter to disable it is:
```
-XX:-TieredCompilation
```
The reason you could achieve higher heap size with other distributions was because on Windows x86 they have both Client and Server VMs and **use the Client VM by default**, while Corretto only has the Server VM at the moment. However, running TeamCity with the Client VM means it would be running with less optimized code compiled by C1.

What makes the difference here is the Code Cache used by the JIT compiler. Since JDK8, Tiered Compilation is enabled by default in the Server VM, and increased the *ReservedCodeCacheSize* to 240Mb, while the default value is just 32Mb for the Client VM and 48Mb for the Server VM without Tiered Compilation. When I set it explicitly to 48Mb with Corretto on the Server VM:
```
-XX:ReservedCodeCacheSize=48M
```
I can achieve the similar heap size as other distributions.

However, it is **NOT** safe to do so with real applications. Tiered Compilation would require more Code Cache. Normally it might require 4-10 times more Code Cache than C2. If you just simply restrict the *ReservedCodeCacheSize*, it would run out of Code Cache pretty soon and you will see the following error message:
```
CodeCache is full. Compiler has been disabled
```

The safe option here is disabling Tiered Compilation. In this way, it can have a similar heap size as the Client VM, at the same time use more optimized code from C2 while running the service. One of the downsides might be that it would require more CPU at the startup. If the CPU cost at the startup time is not an issue for your application, it might be the perfect solution.

We have also tried to build Corretto with both Client and Server VMs on Windows x86. It worked fine and achieved similar result as other distributions. However, we would have to justify whether that gonna be the way to going forward, or the Server VM would be good enough for users.

Please let us know the result of your experiment.

**Comment by yoroto** [comment]
Hi @pavelsher 

Any chance to test the configuration I mentioned above? Thanks!

**Comment by pavelsher** [comment]
Sorry for delay on my side. And thank you for such a detailed explanation! As I remember when we first switched to Java 8 we indeed observed that it used code cache much more aggressively. Turns out it was because of enabled tiered compilation.

I can confirm, disabling the tiered compilation solves the problem. I can now start the application with Xmx up to 1200m. 

I can also see that other vendors 32-bit JVMs also do not start with such a high Xmx and -server argument until I disable tiered compilation there.

We'll consider disabling tiered compilation. An alternative for us is to finally switch to 64-bit JVM by default. But anyway, it seems nothing prevents us from bundling Corretto.

Thank you all for your support!

**Comment by davecurrie** [comment]
@pavelsher Glad to be able to unblock you. As a note, have you noticed any performance differences in TeamCity while running the client vs server VMs? I'd like to know whether the client is still the better VM for your product even though disabling tiered compilation allows the server VM to work for you.
