### ISSUE TITLE
Eclipse and Eclipse-installer fail to run when using Corretto 8

### ISSUE THREAD

**Issue by alvdavi** [corretto/corretto-8#18]
### Description
Attempting to run eclipse or eclipse-installer with corretto8 as the default JDK in Mac 10.12.6 fails while displaying a "Failed to Create the Java Virtual Machine error" popup.

Output when running:
```
$ /Volumes/Eclipse\ Installer/Eclipse\ Installer.app/Contents/MacOS/eclipse-inst

/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home
Error: could not find libjava.dylib
Failed to GetJREPath()
```

libjava.dylib is currently present in:
```
/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre/lib/libjava.dylib
```

Problem does not happen with Oracle/Zulu/AdoptOpenJDK

### To Reproduce
Install corretto and another JDK8 implementation
Try:
```
$ /Applications/Eclipse.app/Contents/MacOS/eclipse -vm /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/bin/java
```
The program failed with:
```
Error: could not find libjava.dylib
Failed to GetJREPath()
```

### Expected behavior
Eclipse and Eclipse-Installer should start when using corretto

### Platform information
    OS: macOS High Sierra 10.13.6
    Version: build 1.8.0_192-amazon-corretto-preview-b12

**Comment by ziyiluo** [comment]
This issue is fixed in the new Corretto preview release (1.8.0_192-amazon-corretto-preview2-b12). Change log of this release is now [available](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html). You can find the builds in the [Corretto download page](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html). Please let us know if you have any further questions. We appreciate your report!
