### ISSUE TITLE
Supporting Corretto 8 on windows 2019

### ISSUE THREAD

**Issue by arpitgautam** [corretto/corretto-8#206]
Are there any plans to support Corretto 8 on Windows 2019 in near future?

**Comment by davecurrie** [comment]
@arpitgautam Windows 2019 is already supported. We will update the relevant docs, thanks for pointing it out.

**Comment by sangirash** [comment]
Can you please confirm which update of Corretto 8 is supported. We are using update 202 and would like to see if following issue in particular is addressed there... https://bugs.openjdk.java.net/browse/JDK-8220415
As per the update @ https://github.com/corretto/corretto-8/issues/92 this issue is addressed in update 212 but just want to check whether this is addressed for 20 as well. Can you please confirm ?

**Comment by alvdavi** [comment]
Once a new minor version of Corretto is released, no further work is done on previous minor versions. 

Corretto8 version numbers look like:
```
8.<minor_version>.<build_number>.<corretto_revision>
```

Whenever a bug is found, it will be normally be fixed in the next Corretto8 minor version update. In some situations, an update of the current Corretto8 minor version will be done. In this case, this will cause the corretto_revision part of the version number to be updated.

We strongly encourage the usage of the latest Corretto8 available artifacts. Every Corretto8 minor_version update includes the latest security fixes. The usage of Corretto (or any other OpenJDK implementation) without these security fixes may put your systems at risk.
