### ISSUE TITLE
Why includes OpenJDK sources in the Debian package?

### ISSUE THREAD

**Issue by orisano** [corretto/corretto-8#229]
This is just a question.

### Is your feature request related to a problem?
No.

### Describe a solution you would like
Why includes OpenJDK sources in the Debian package?
Currently, src.zip is 50MB of 300MB(`amazoncorretto` container image).

**Comment by yoroto** [comment]
Hi @orisano 

Thank you for reporting this! We will discuss whether to remove it in the future release.

**Comment by guidomedina** [comment]
I know this is merged but I wonder from an IDE perspective how can one access the JDK sources? for example in the case of OpenJDK you usually install two packages:
- openjdk-8
- openjdk-8-sources

I'm not saying the sources should be somehow includes with the JRE jars but there has to be a way to have this which is good for developers that like to see what JRE source is doing, I like to look at the source code of my call to see if it is done optimally or I or any other API can do a better job.

**Comment by ziyiluo** [comment]
There's a long debate in the Corretto team regarding which option serves Corretto users the best. Here are some of the different use cases we learned from Corretto users, which lead to different packaging plan:
1. For normal use cases, a "fat" rpm/deb is enough:
  * corretto-jdk
2. For those who wish to have a jre:
  * corretto-jre
  * corretto-jdk (depends on corretto-jre)
3. For those who wish to have a separate source package:
  * corretto-jre
  * corretto-jdk (depends on corretto-jre)
  * corretto-source
4. For those who wish to have headful and headless jdk & jre packages:
  * corretto-jre-headless
  * corretto-jdk-headless (depends on corretto-jre-headless)
  * corretto-jre (depends on corretto-jre-headless)
  * corretto-jdk (depends on corretto-jdk-headless)
  * corretto-source

Use cases 2-4 are complicated for users of use case 1. Unless using the Corretto apt/rpm repository, installing multiple .deb/.rpm is not really a pleasant user experience. Supporting all use cases is like, "To start using Corretto, you need to fully understand what are JDK and JRE and how they work on your system so that you know which package to choose" :).The discussion is still undergoing. We will update the issue when there's a decision.

**Comment by guidomedina** [comment]
Yeah, I see now all the complications.

Even if 4 is not comprehended by most Java users it would still be "kind of" the correct thing to do if you were to emulate how OpenJDK does it today, but maybe option 3 is a good compromise and much less confusing.

TBH I don't mind which option is picked but for consistency I tend to set the same JDK I plan to use or I'm using in production on the dev environment, **i.e.:** IntelliJ; having the source code is nice for some Java users.

It is not something that you would need to install on a node/server of course so it is also understandable why most people would hate the fat option(s)

I think the headless part brings more confusion, someone could be doing some server side and also image processing or whatever (no idea since I only deal with backend stuff) which would require some of the graphical stuff that is excluded by the headless packages which is why I don't think option number 3 is too bad.

**Comment by davecurrie** [comment]
To get some closure here, we may decide to deliver additional package types in the future if there is a strong reason to do so. It is very unlikely that we will be removing or significantly changing existing packages because of the backwards-compatibility implications.
