### ISSUE TITLE
Corretto macOS installer - AWS logo is partially hidden

### ISSUE THREAD

**Issue by wolruf** [corretto/corretto-8#30]
### Describe the bug
Corretto macOS installer - AWS logo is partially hidden

### To Reproduce
Download https://d3pxv6yz143wms.cloudfront.net/corretto-jdk-8u192-macosx-x64.pkg
Install on macOS High Sierra 10.13.6
Installer displays instructions with AWS logo partially obstructed.

### Expected behavior
AWS logo fully visible

### Screenshots
<img width="613" alt="screen shot 2018-12-13 at 13 18 06" src="https://user-images.githubusercontent.com/13536363/49938465-42181400-feda-11e8-96ef-49fe745ecfe6.png">

### Platform information
    OS: macOS 10.13.6
    Version: openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)

**Comment by gdams** [comment]
What tool is being used to create the installers? Most installers don't even show the logo on newer versions of macOS anymore but strangely the Corretto one does.

**Comment by ziyiluo** [comment]
Hi @wolruf, thanks for bringing this up :). We will resize the AWS logo so it will display properly on the sidebar of the installer. This will be addressed in the next preview release.

**Comment by ziyiluo** [comment]
@gdams Sorry for the late response. We use the `packagesbuild` utility tool to generate the installer. The installer configuration file (.pkgproj) allows you to specify the background image of the installer by adding a `BACKGROUND` key under dict `PROJECT.PROJECT_PRESENTATION`.

**Comment by ziyiluo** [comment]
This issue is fixed in the new Corretto preview release (1.8.0_192-amazon-corretto-preview2-b12). Change log of this release is now [available](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html). You can find the builds in the [Corretto download page](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html). Please let us know if you have any further questions. We appreciate your report!
