### ISSUE TITLE
Latest release api page seems to be Mac only - name is 'Mac M1 8.322.06.4'

### ISSUE THREAD

**Issue by TheEnglishman-1966** [corretto/corretto-8#367]
When connecting to  'https://api.github.com/repos/corretto/corretto-8/releases/latest' 
the 'name' is 'Mac M1 8.322.06.4'

Shouldn't the 'latest release' page be processor agnostic?

**Comment by lutkerd** [comment]
Hi, sorry for the inconvenience on this. We don't always release all platforms for a specific version. This latest release was only for Mac M1 and since there were some code changes specific to the platform we incremented the version number. 

We do also publish a complete JSON with all of the latest releases across versions and platforms which you can find from https://corretto.github.io/corretto-downloads/. Specifically, https://corretto.github.io/corretto-downloads/latest_links/indexmap_with_checksum.json, will always contains our latest stable releases and hashes.

**Comment by navyxliu** [comment]
hi, @TheEnglishman-1966 
May I close this issue?  To keep tabs on processor-agnostic releases, you can consume https://corretto.github.io/corretto-downloads/latest_links/indexmap_with_checksum.json

**Comment by TheEnglishman-1966** [comment]
You may indeed close this.  And thanks for clarifying the release page.
