### ISSUE TITLE
Provide Windows installer option to skip system-wide environment changes

### ISSUE THREAD

**Issue by glucas** [corretto/corretto-8#50]
With recent changes (#39, #40, #43) the Windows installer makes a number of environment changes that may not be desirable when installing multiple JVMs on a machine (e.g. a CI build agent or a developer laptop for working on multiple projects). 

Could the installer provide an option to skip these steps?

**Comment by glucas** [comment]
Thanks, can we do that via silent installer?

**Comment by yoroto** [comment]
Yes, it is an installation feature so you can use msiexec options to exclude it.

Alternatively, since we also provide Corretto JDK and JRE in .zip format. You can just unzip them to wherever you want. That would probably be even easier for you.

We will make the .jar file association a feature option in the future release so you can exclude it if you want.

**Comment by glucas** [comment]
Great, thanks!
