### ISSUE TITLE
Windows 32bit msi Installer does not add standard registry keys

### ISSUE THREAD

**Issue by JS-GH** [corretto/corretto-8#54]
Issue was identified in Corretto Windows **32bit msi** installers:

With recent changes (#14, #40) the 64 bit Windows MSI installer creates registry entries
_[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft]\Java Development Kit\..._  and
_[HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft]\Java Runtime Environment\..._
 which is great for compatibility with Oracle Java installations.

Unfortunately these registry keys are **ONLY** generated by the **64bit MSI** installer, but **NOT** by the **32bit MSI** installer. Problem is reproducable with 8u192-windows-x86.msi and 8u202-windows-x86.msi. Tested with Windows 10 Pro.

**Comment by davecurrie** [comment]
@JS-GH Thanks for bringing this up. We'll verify this and update the issue when we have more information on a fix.

**Comment by yoroto** [comment]
Hi @JS-GH 

I assume you were installing the x86 Corretto on an x64 Windows 10 machine. The registry keys would be under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node, rather than HKEY_LOCAL_MACHINE\SOFTWARE. You will find this behavior for most x86 applications running on x64 Windows, for example, Oracle JDK as well. If you need more information on this, you can refer. to the Microsoft document on this: https://docs.microsoft.com/en-us/windows/desktop/WinProg64/registry-redirector .

**Comment by JS-GH** [comment]
Thanks for clarification :+1:
